name: pix_revive
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  gap: ^3.0.1
  go_router: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true



  assets:
    - assets/Icons/

  fonts:
    - family: Inter_18
      fonts:
        - asset: assets/Fonts/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/Fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/Fonts/Inter_24pt-SemiBold.ttf
          weight: 600   
